holiday_house/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rental.urls')),
    path('accounts/', include('login.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login, name='login'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_up/2', views.sign_up_two, name='sign_up_two'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('request_password_reset/', views.request_password_reset, name='request_password_reset'),
    path('password_reset/', views.password_reset, name='password_reset'),
]

login/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe




class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} - {self.created_timestamp} - {self.updated_timestamp} - {self.token}'

login/views.py
from django.shortcuts import render, reverse
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from login.models import PasswordResetRequest


def login(request):
    context = {}

    if request.method == "POST":
        user = authenticate(request, username=request.POST['user'], password=request.POST['password'])
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('rental:index'))
        else:
            context = {
                'error': 'Bad username or password.'
            }
    return render(request, 'login/login.html', context)


def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('login:login'))


def password_reset(request):
    pass


def sign_up(request):
    context = {}
    if request.method == "POST":
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        user_name = request.POST['user']
        email = request.POST['email']
        if password == confirm_password:
            if User.objects.create_user(user_name, email, password):
                return HttpResponseRedirect(reverse('login:login'))
            else:
                context = {
                    'error': 'Could not create user account - please try again.'
                }
        else:
            context = {
                'error': 'Passwords did not match. Please try again.'
            }

    return render(request, 'login/sign_up.html', context)


@login_required()
def sign_up_two(request):
    if request.method == "POST":
        user = User.objects.get(pk=request.user.pk)
        user.last_name = request.POST['last_name']
        user.first_name = request.POST['first_name']
        user.save()

        return HttpResponseRedirect(reverse('rental:index'))

    return render(request, 'login/sign_up_two.html')


def request_password_reset(request):
    if request.method == "POST":
        post_user = request.POST['username']
        user = None

        if post_user:
            try:
                user = User.objects.get(username=post_user)
            except:
                print(f"Invalid password request: {post_user}")
        else:
            post_user = request.POST['email']
            try:
                user = User.objects.get(email=post_user)
            except User.DoesNotExist:
                print(f"Invalid password request: {post_user}")
        if user:
            prr = PasswordResetRequest()
            prr.user = user
            prr.save()
            print(prr)

            send_mail(
                'Reset your password',
                F"This is your reset link: {reverse('login:password_reset')}/{prr}",
                'login@django.com',
                [user.email],
                fail_silently=False,
            )

            return HttpResponseRedirect(reverse('login:password_reset'))

    return render(request, 'login/request_password_reset.html')


def password_reset(request):
    if 'token' in request.GET:
        context = {
            'token': request.GET['token']
        }
    else:
        context = {}

    if request.method == "POST":
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            if request.user.is_authenticated:
                user = request.user

            else:
                token = request.POST['token']

                try:
                    prr = PasswordResetRequest.objects.get(token=token)
                    prr.save()

                except PasswordResetRequest.DoesNotExist:
                    print("Invalid password reset attempt.")
                    return render(request, 'login/password_reset.html')

                user = prr.user

        user.set_password(password)
        user.save()
        return HttpResponseRedirect(reverse('login:login'))

    return render(request, 'login/password_reset.html', context)


@login_required
def delete_account(request):
    if request.method == "POST":
        if request.POST['confirm_deletion'] == "DELETE":
            user = authenticate(request, username=request.user.username, password=request.POST['password'])
            if user:
                print(f"Deleting user {user}")
                user.delete()
                return HttpResponseRedirect(reverse('login:login'))
            else:
                print("fail delete")

    return render(request, 'login/delete_account.html')

login/templates/login/delete_account.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Delete Account</title>
</head>
<body>
   <h1>Delete Account</h1>
   <hr />
   <form action="{% url 'login:delete_account'%}" method="POST">
      {% csrf_token %}
      <input type="password" name="password" placeholder="Password">
      <br />
      <input type="text" name="confirms_deletion" placeholder="TYPE DELETE">
      <br />
      <button>Submit</button>
   </form>
   <hr />
</body>
</html>

login/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Login</title>
</head>
<body>
   <h1>Login</h1>
   <a href="{% url 'login:sign_up' %}">Sign Up</a>
   <hr />
      <form action="{% url 'login:login' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="user" placeholder="User Name">
            <input type="password" name="password" placeholder="Password">
            <button>Login</button>
      </form>
   <hr />
   {% if error %}
      {{ error }}
   {% endif %}
   <a href="{% url 'login:request_password_reset' %}">Request Password Reset</a>
</body>
</html>

login/templates/login/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password</title>
</head>
<body>
<h1>Reset Password</h1>
<hr/>
<form action="{% url 'login:password_reset' %}" method="POST">
    {% csrf_token %}
    <input type="password" name="password" placeholder="New Password">
    <br/>
    <input type="password" name="confirm_password" placeholder="Repeat New Password">
    <br/>
    {% if not user.is_authenticated %}
        <input type="hidden" name="token" placeholder="Token" value="{{ token }}">
    {% endif %}
    <br/>
    <button>Submit</button>
</form>
<hr/>
</body>
</html>

login/templates/login/request_password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Request Password Reset</title>
</head>
<body>
   <h1>Request Password Reset</h1>
   <hr />
      <form action="{% url 'login:request_password_reset' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="User Name">
            <button>Submit</button>
      </form>
   <hr />
</body>
</html>

login/templates/login/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Sign Up</title>
</head>
<body>
   <h1>Sign Up</h1>
   <hr />
   <form action="{% url 'login:sign_up' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="user" placeholder="User Name">
       <input type="email" name="email" placeholder="Email Address">
      <input type="password" name="password" placeholder="Password">
      <input type="password" name="confirm_password" placeholder="Confirm Password">
      <button>Continue</button>
   </form>
   <hr />
   {% if error %}
      {{ error }}
   {% endif %}
</body>
</html>

login/templates/login/sign_up_two.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Sign Up</title>
</head>
<body>
   <h1>Sign Up</h1>
   <hr />
   <form action="{% url 'login:sign_up_two' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="first_name" placeholder="First name">
      <input type="text" name="last_name" placeholder="Last name">
      <button>Sign up</button>
   </form>
   <hr />
   {% if error %}
      {{ error }}
   {% endif %}
</body>
</html>