holiday_house/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rental.urls')),
    path('accounts/', include('login.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login, name='login'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_up/2', views.sign_up_two, name='sign_up_two'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('request_password_reset/', views.request_password_reset, name='request_password_reset'),
    path('password_reset/', views.password_reset, name='password_reset'),
]

rental/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'rental'

urlpatterns = [
    path('', views.index, name='index'),
    path('property/<int:pk>', views.single_property, name='property'),
    path('booking/create', views.create_booking, name='booking_create'),
]

rental/models.py
from django.contrib.auth.models import User
from django.db import models
import uuid


class RealCharField(models.Field):
    def db_type(self, connection):
        return 'CHAR'


class Country(models.Model):
    name = models.CharField(max_length=50)
    country_code = RealCharField(max_length=3)

    def __str__(self):
        return f'name={self.name} - country_code={self.country_code}'


class City(models.Model):
    name = models.CharField(max_length=26)
    country = models.ForeignKey(Country, on_delete=models.PROTECT)

    def __str__(self):
        return f'name={self.name} - country={self.country}'


class Zip(models.Model):
    zip = models.IntegerField()
    city = models.ForeignKey(City, on_delete=models.PROTECT)

    def __str__(self):
        return f'zip_code={self.zip} - city={self.city}'


class Property(models.Model):
    title = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=0, default=0)
    address = models.CharField(max_length=100)
    zip = models.ForeignKey(Zip, on_delete=models.PROTECT)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    bedrooms = models.CharField(max_length=2)
    bathrooms = models.CharField(max_length=2)
    accommodates = models.CharField(max_length=2)
    description = models.CharField(max_length=1000)


    def __str__(self):
        return f'title={self.title} - price={self.price} - address={self.address} - zip={self.zip} - owner={self.owner}'


class PropertyImg(models.Model):
    property = models.ForeignKey(Property, related_name='property_img', on_delete=models.CASCADE)
    img = models.ImageField()
    order = models.IntegerField()

    def __str__(self):
        return f'property={self.property} - img={self.img} - order={self.order}'


class Booking(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return f'property={self.property} - customer={self.customer} - start_date={self.start_date} - ' \
               f'end_date={self.end_date}'


class Role(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f'name={self.name}'


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name="user_profile", on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.PROTECT)
    address = models.CharField(max_length=100)
    zip = models.ForeignKey(Zip, on_delete=models.PROTECT)
    phone = models.CharField(max_length=20)

    def __str__(self):
        return f'user={self.user} - role={self.role} - address={self.address} - zip={self.zip}'

rental/views.py
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.http import require_http_methods
from django.urls import reverse
from django.shortcuts import render
from .models import Property, PropertyImg, Booking


def index(request):
    if request.method == 'POST':
        if 'search_field' in request.POST:
            search_input = request.POST['search_field']
            query = request.POST['search_field']
            try:
                properties = Property.objects.filter(Q(zip__zip=int(search_input)))
            except:
                properties = Property.objects.filter(Q(address__iexact=search_input) |
                                                     Q(zip__city__name__iexact=search_input) |
                                                     Q(zip__city__country__name__iexact=search_input))
    else:
        properties = Property.objects.all()
        query = ''

    context = {
        'properties': properties,
        'query': query
    }
    return render(request, "rental/index.html", context)


def single_property(request, pk):
    property_item = Property.objects.get(pk=pk)
    property_images = PropertyImg.objects.filter(property=property_item).order_by('order')

    context = {
        'property': property_item,
        'images': property_images
    }

    return render(request, 'rental/property.html', context)


@require_http_methods(["POST"])
def create_booking(request, *args, **kwargs):
    Booking.objects.create(
        customer=request.user,
        property=Property.objects.get(pk=request.POST['property']),
        start_date=request.POST['start_date'],
        end_date=request.POST['end_date']
    )

    return HttpResponseRedirect(reverse('rental:index'))

rental/templates/rental/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/rental.css' %}" media="screen"/>
    <title>Holiday House</title>
</head>
<body>
<section class="top-bar">
    <a class="logo" href="{% url 'rental:index' %}"><h1>Holiday house</h1></a>
    <input type="checkbox" id="navControl">
    <label class="burger" for="navControl"></label>
    <nav>
        {% if request.user.is_authenticated %}
        <p>Welcome {{ user }} - <a href="{% url 'login:logout' %}">Log out</a></p>
        {% else %}
        <a href="{% url 'login:login' %}">Log in</a>
        {% endif %}
    </nav>
</section>

<main>
    {% block content %}
    {% endblock %}
</main>
<footer>
    {% block footer %}
    {% endblock %}
</footer>
</body>
</html>

rental/templates/rental/index.html
{% extends "rental/base.html" %}

{% block content %}

<section class="grid-center">
    <form class="search" action="{% url 'rental:index'%}" method="post">
        {% csrf_token %}
        <input type="text" name="search_field" value="{{query}}">
        <button type="submit">🔍</button>
    </form>

    <ul class="accessories">
        <li>Pool</li>
        <li>Jacuzzi</li>
        <li disabled="">Sauna</li>
        <li disabled="">Balcony</li>
    </ul>
</section>


<section class="properties">
    {% for property in properties %}
    <a href="{% url "rental:property" property.pk %}">
        <article class="grid-2-col">
            <img class="rounded" src="{{ MEDIA_URL }}{{ property.property_img.first.img }}" alt="{{ property_img.img }}">
            <section>
                <p><b>{{property.title}}</b></p>
                <p>Price: {{property.price}}DKK</p>
                <p class="description">{{property.description}}</p>
            </section>
        </article>
    </a>

    {% endfor %}
</section>
{% endblock %}

rental/templates/rental/property.html
{% extends "rental/base.html" %}

{% block content %}
    <section class="top-image">
        <img src="{{ MEDIA_URL }}/{{ images.0.img }}" alt="header-image">
        <p>{{ property.title }}</p>
    </section>


    <section class="grid-2-col">
        <section class="booking">
            <input type="checkbox" id="bookingControl">
            <label class="button" for="bookingControl"></label>
            <form action="{% url 'rental:booking_create' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="property" value="{{property.pk}}">
                <label for="start_date">Start date</label>
                <input type="date" id="start_date" name="start_date">
                <label for="end_date">End date</label>
                <input type="date" id="end_date" name="end_date">
                <button>Make booking</button>
            </form>
                <ul class="accessories">
                    <li>Pool</li>
                    <li>Jacuzzi</li>
                </ul>
        </section>

        <section>
            <p><b>Email</b>: {{ property.owner.email }}</p>
            <p><b>Phone</b>: {{ property.owner.user_profile.phone }}</p>
        </section>
    </section>

   <section class="grid-2-col">
       <section>
           <p><b>Country</b>: {{ property.zip.city.country.name }}</p>
           <p><b>City</b>: {{ property.zip.city.name }}</p>
           <p><b>Price</b>: {{ property.price }}</p>
       </section>
       <section>
           <p><b>Bedrooms</b>: {{ property.bedrooms }}</p>
           <p><b>Bathrooms</b>: {{ property.bathrooms }}</p>
           <p><b>Accommodate</b>s: {{ property.accommodates }}</p>
       </section>
   </section>

    <section class="grid-2-col">
        <img class="rounded" src="{{ MEDIA_URL }}/{{ images.1.img }}" alt="highlighted image">
        <img class="rounded" src="{{ MEDIA_URL }}/{{ images.2.img }}" alt="highlighted image">
    </section>

    <section class="slider-images">
        {% for image in images %}
            <img src="{{ MEDIA_URL }}/{{ image.img }}">
        {% endfor %}
    </section>

    <section class="grid-1-col">
        <p><b>Description</b>:</p>
        <p>{{ property.description }}</p>
    </section>
{% endblock %}